export const INTERVIEW_LIST_REQUEST = "INTERVIEW_LIST_REQUEST";
export const INTERVIEW_LIST_SUCCESS = "INTERVIEW_LIST_SUCCESS";
export const INTERVIEW_LIST_FAIL = "INTERVIEW_LIST_FAIL";

export const INTERVIEW_CREATE_REQUEST = "INTERVIEW_CREATE_REQUEST";
export const INTERVIEW_CREATE_SUCCESS = "INTERVIEW_CREATE_SUCCESS";
export const INTERVIEW_CREATE_FAIL = "INTERVIEW_CREATE_FAIL";